services:
  web:
    image: ghcr.io/master-hash/naiveproxy:2.10.2-cloudflare
    restart: always
    ports:
      - 443:443
      # - 443:443/udp
    volumes:
      - caddy_data:/data
    environment:
      - DNSAPI=some-cloudflare-api
      - CADDY_HOSTNAME=caddy.example.com
      - CADDY_USERNAME=example-user
      - CADDY_PASSWORD=example-pass
volumes:
  caddy_data:
