name: Build

on:
  # workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "caddy/**"
      - ".github/workflows/caddy.yml"

env:
  REGISTRY_IMAGE: ghcr.io/master-hash/naiveproxy

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v6

      # When GitHub ships Docker CE 29 by default, we can remove this step
      - uses: docker/setup-docker-action@v4
        with:
          version: latest
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - uses: actions/cache@v4
        with:
          path: go-build-cache
          key: ${{ runner.os }}-go-build-cache }}

      - name: Inject go-build-cache
        uses: reproducible-containers/buildkit-cache-dance@4b2444fec0c0fb9dbf175a96c094720a692ef810 # v2.1.4
        with:
          cache-source: go-build-cache

      - run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x \
            --label "${DOCKER_METADATA_OUTPUT_LABELS//$'\n'/,}" \
            -t ${{ env.REGISTRY_IMAGE }}:2.11.0-beta.1-cloudflare-uot-compat \
            --output type=registry,compression=gzip \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            .
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x \
            --label "${DOCKER_METADATA_OUTPUT_LABELS//$'\n'/,}" \
            -t ${{ env.REGISTRY_IMAGE }}:2.11.0-beta.1-cloudflare-uot \
            --output type=registry,compression=zstd,compression-level=22,force-compression=true,oci-mediatypes=true,oci-artifact=true \
            .
        working-directory: caddy
